# Generated by Django 6.0.5 on 2026-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_encomienda_codigo_alter_encomienda_costo_envio_and_more'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta'),
        ),
    ]
